
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout of Repo
      uses: actions/checkout@v4
    - name: Use Node.js 16.14
      uses: actions/setup-node@v4
      with:
        node-version: 16.14
        cache: 'npm'
    - name: Install dependancies 
      run:  npm install 
    # - name: Install dependancies Back End
    #   run: cd server && npm install 
    - name: Run Back-End
      run: npm start &
    - name: Run Front-End
      run: npm start &
   
